import { Fragment } from "react";
import Head from "next/head";
import { AppProps } from "next/app";

import CssBaseline from "@mui/material/CssBaseline";
import { MessageProvider } from "@/context/messageContext";

function AppPage({ Component, pageProps }: AppProps) {
  return (
    <Fragment>
      <Head>
        <title>Echo Bot</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <MessageProvider>
        <Component {...pageProps} />
      </MessageProvider>
    </Fragment>
  );
}

export default AppPage;
